# Generated by Django 6.0.6 on 2026-07-30 17:56

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='Categoria')),
                ('margem_padrao_percentual', models.DecimalField(decimal_places=2, default=Decimal('60.00'), help_text='Usada para sugerir o preço de venda ao cadastrar um produto desta categoria.', max_digits=6, verbose_name='Margem padrão sugerida (%)')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True, verbose_name='Nome')),
                ('telefone', models.CharField(blank=True, max_length=30, verbose_name='Telefone')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_local', models.CharField(max_length=50, unique=True, verbose_name='Nome do local')),
            ],
            options={
                'verbose_name': 'Local de Armazenamento',
                'verbose_name_plural': 'Locais de Armazenamento',
                'ordering': ['nome_local'],
            },
        ),
        migrations.CreateModel(
            name='Orcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_nome_avulso', models.CharField(blank=True, max_length=255, verbose_name='Nome do cliente (avulso)')),
                ('data', models.DateField(default=django.utils.timezone.localdate, verbose_name='Data do orçamento')),
                ('validade_orcamento', models.DateField(blank=True, null=True, verbose_name='Válido até')),
                ('status', models.CharField(choices=[('ABERTO', 'Aberto'), ('CONVERTIDO', 'Convertido em venda'), ('EXPIRADO', 'Expirado')], default='ABERTO', max_length=20)),
                ('observacoes', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orcamentos', to='suplementos.cliente', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Orçamento',
                'verbose_name_plural': 'Orçamentos',
                'ordering': ['-data', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=255, verbose_name='Nome do Produto')),
                ('marca', models.CharField(blank=True, max_length=100, verbose_name='Marca')),
                ('variacao', models.CharField(blank=True, max_length=100, verbose_name='Variação (Sabor/Tamanho)')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='produtos/', verbose_name='Imagem')),
                ('quantidade', models.IntegerField(default=0, verbose_name='Quantidade')),
                ('quantidade_minima', models.IntegerField(default=1, verbose_name='Quantidade mínima (alerta de estoque baixo)')),
                ('p_compra', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço de Compra')),
                ('p_venda', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço de Venda')),
                ('validade', models.DateField(blank=True, null=True, verbose_name='Data de validade')),
                ('obs', models.TextField(blank=True, verbose_name='Observações')),
                ('status', models.CharField(choices=[('OK', 'Ok'), ('BAIXO', 'Baixo'), ('ESGOTADO', 'Esgotado')], default='OK', max_length=20, verbose_name='Status')),
                ('legacy_id', models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos', to='suplementos.categoria', verbose_name='Categoria')),
                ('local', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos', to='suplementos.local', verbose_name='Local de Armazenamento')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['nome_produto'],
            },
        ),
        migrations.CreateModel(
            name='ItemOrcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto_snapshot', models.CharField(max_length=255)),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('preco_unit_venda', models.DecimalField(decimal_places=2, max_digits=10)),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='suplementos.orcamento')),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_orcamento', to='suplementos.produto')),
            ],
            options={
                'verbose_name': 'Item de Orçamento',
                'verbose_name_plural': 'Itens de Orçamento',
            },
        ),
        migrations.CreateModel(
            name='Promocao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('DESCONTO', 'Desconto'), ('COMBO', 'Combo')], default='DESCONTO', max_length=20)),
                ('nome', models.CharField(max_length=255, verbose_name='Nome da promoção')),
                ('percentual_desconto', models.DecimalField(blank=True, decimal_places=2, help_text='Usado quando o tipo é Desconto.', max_digits=5, null=True)),
                ('preco_fechado', models.DecimalField(blank=True, decimal_places=2, help_text='Preço fechado do combo (soma de todos os produtos incluídos).', max_digits=10, null=True)),
                ('data_inicio', models.DateField(default=django.utils.timezone.localdate)),
                ('data_fim', models.DateField()),
                ('ativo', models.BooleanField(default=True)),
                ('observacoes', models.TextField(blank=True)),
                ('produtos', models.ManyToManyField(blank=True, related_name='promocoes', to='suplementos.produto')),
            ],
            options={
                'verbose_name': 'Promoção',
                'verbose_name_plural': 'Promoções',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forma_pagamento', models.CharField(choices=[('DINHEIRO', 'Dinheiro'), ('PIX', 'Pix'), ('CARTAO', 'Cartão'), ('FIADO', 'Fiado')], default='DINHEIRO', max_length=20)),
                ('data', models.DateField(default=django.utils.timezone.localdate, verbose_name='Data da venda')),
                ('pago', models.BooleanField(default=True, verbose_name='Pago')),
                ('data_pagamento', models.DateField(blank=True, null=True, verbose_name='Data do pagamento')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('legacy_id', models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendas', to='suplementos.cliente', verbose_name='Cliente')),
                ('local', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendas', to='suplementos.local', verbose_name='Local')),
            ],
            options={
                'verbose_name': 'Venda',
                'verbose_name_plural': 'Vendas',
                'ordering': ['-data', '-id'],
            },
        ),
        migrations.AddField(
            model_name='orcamento',
            name='venda_gerada',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orcamento_origem', to='suplementos.venda'),
        ),
        migrations.CreateModel(
            name='VendaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto_snapshot', models.CharField(max_length=255)),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('preco_unit_venda', models.DecimalField(decimal_places=2, max_digits=10)),
                ('preco_unit_custo', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_venda', to='suplementos.produto')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='suplementos.venda')),
            ],
            options={
                'verbose_name': 'Item de Venda',
                'verbose_name_plural': 'Itens de Venda',
            },
        ),
    ]
