# Generated by Django 6.0.6 on 2026-06-22 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_local', models.CharField(max_length=50, unique=True, verbose_name='Nome do local')),
            ],
            options={
                'verbose_name': 'Local de Armazenamento',
                'verbose_name_plural': 'Locais de Armazenamento',
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produto', models.CharField(max_length=255, verbose_name='Nome do Produto')),
                ('marca', models.CharField(max_length=100, verbose_name='Marca')),
                ('variacao', models.CharField(blank=True, max_length=100, null=True, verbose_name='Variação (Sabor/Tamanho)')),
                ('quantidade', models.IntegerField(default=0, verbose_name='Quantidade')),
                ('p_compra', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço de Compra')),
                ('p_venda', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço de Venda')),
                ('status', models.CharField(choices=[('OK', 'Ok'), ('BAIXO', 'Baixo'), ('ESGOTADO', 'Esgotado')], default='OK', max_length=20, verbose_name='Status')),
                ('local', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos', to='suplementos.local', verbose_name='Local de Armazenamento')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
    ]
