# Generated by Django 6.0.6 on 2026-08-11 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suplementos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='imagem',
        ),
    ]
